"""Build shared shells, navigation and directories with Python's standard library.

Run from any directory: python scripts/build_site.py [--check]
Existing article bodies and interactions are never regenerated.
"""
from pathlib import Path
import argparse
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'content-index.json').read_text(encoding='utf-8'))
TOPICS = {item['id']: item for item in DATA['topics']}
ENTRIES = DATA['entries']
OUTPUTS = {}

def esc(value):
    return html.escape(str(value), quote=True)

def prefix(path):
    return '../' * (len(Path(path).parts) - 1)

def head(path, extra=''):
    base = prefix(path)
    return '\n'.join([
        f'<link rel="stylesheet" href="{base}assets/css/tokens.css">',
        f'<link rel="stylesheet" href="{base}assets/css/site.css">', extra,
        f'<script src="{base}assets/js/site.js" defer></script>'
    ])

def header(path, active, target='lf-content'):
    base = prefix(path)
    links = [('index.html','首页','home'),('topics.html','专题','topics'),('diagrams.html','图解实验','diagrams'),('work/','工作文档','work'),('resume-weixin_43960572.html','关于我','about')]
    nav = ''.join(f'<a href="{base}{url}"'+(' aria-current="page"' if key == active else '')+f'>{label}</a>' for url,label,key in links)
    return f'''<a class="lf-skip" href="#{target}">跳到正文</a>
<header class="lf-header"><div class="lf-header-inner">
  <a class="lf-brand" href="{base}index.html"><span class="lf-brand-mark" aria-hidden="true">L</span>Linkforfuture</a>
  <div class="lf-nav" role="navigation" aria-label="全站导航">{nav}</div>
  <details class="lf-menu"><summary>导航</summary><div class="lf-nav" role="navigation" aria-label="移动端全站导航">{nav}</div></details>
</div></header>'''

def footer(path):
    base = prefix(path)
    return f'''<footer class="lf-footer"><div class="lf-footer-inner"><span>Linkforfuture · 记录学习、工作与思考</span><div class="lf-footer-links"><a href="https://github.com/linkforfuture/linkforfuture.github.io">GitHub</a><a href="{base}topics.html">全部内容</a><a href="{base}resume-weixin_43960572.html#learning-path">学习路径</a></div></div></footer>'''

def document(path, title, description, content, active, scripts=''):
    return f'''<!doctype html>
<html lang="zh-CN"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{esc(description)}"><title>{esc(title)} · Linkforfuture</title>
{head(path)}
</head><body class="lf-site" data-page="{active}">
<!-- Generated by scripts/build_site.py. Edit content-index.json or the generator, then rebuild. -->
{header(path,active)}
<main class="lf-container" id="lf-content">{content}</main>
{footer(path)}{scripts}
</body></html>
'''

def entry_row(item):
    topic = TOPICS[item['topic']]['title']
    return f'''<article class="lf-entry" data-lf-entry data-topic="{esc(item['topic'])}"><div><a class="lf-entry-title" href="{esc(item['url'])}">{esc(item['title'])}</a><p>{esc(item['summary'])}</p></div><div class="lf-entry-meta"><span>{esc(topic)}</span><span class="lf-tag">{esc(item['kind'])}</span></div></article>'''

def homepage():
    cards=[]
    for topic in DATA['topics']:
        count=sum(item['topic']==topic['id'] and item['kind']!='关于我' for item in ENTRIES)
        cards.append(f'''<a class="lf-topic" href="topics.html#{topic['id']}"><small>{topic['label']}</small><h3>{topic['title']}</h3><p>{topic['description']}</p><span class="lf-count">{count} 篇内容 →</span></a>''')
    featured='\n'.join(entry_row(item) for item in ENTRIES if item.get('featured'))
    content=f'''<section class="lf-home-hero"><div><span class="lf-kicker">NOTES / SYSTEMS / EXPERIMENTS</span><h1 class="lf-title">集合通信与<br>AI 基础设施。</h1><p class="lf-lead">记录系统如何工作，也记录我如何理解它。<br>从 HCCL 与 GPU 编程，到算法推导和动手实验。</p><div class="lf-actions"><a class="lf-button lf-button-primary" href="topics.html">浏览技术专题 →</a><a class="lf-button" href="resume-weixin_43960572.html">关于我</a></div></div><aside class="lf-focus"><span class="lf-kicker">LEARNING IN PRACTICE</span><h2>从理解原理，到动手验证</h2><p>以集合通信研发为起点，逐步学习 CUDA、NCCL 与训练通信。</p><a href="resume-weixin_43960572.html#learning-path">查看 12 周学习路径 →</a></aside></section>
<section class="lf-section" aria-labelledby="lf-topics-title"><div class="lf-section-head"><h2 id="lf-topics-title">沿着专题阅读</h2><a href="topics.html">全部专题 →</a></div><div class="lf-topic-grid">{''.join(cards)}</div></section>
<section class="lf-section" aria-labelledby="lf-featured-title"><div class="lf-section-head"><h2 id="lf-featured-title">精选内容</h2><a href="diagrams.html">探索图解实验 →</a></div>{featured}</section>
<section class="lf-section lf-note"><h2>工作中的设计与分析</h2><p>需求规格、系统设计、拓扑解析与问题定位，按原有文档目录持续整理。</p><a href="work/">进入工作文档 →</a></section>'''
    OUTPUTS['index.html']=document('index.html','个人主页','集合通信、GPU 编程、算法与模型推理的个人技术笔记。',content,'home')

def directory(diagrams=False):
    path='diagrams.html' if diagrams else 'topics.html'
    title='图解实验' if diagrams else '技术专题'
    description='在图解与实验中理解数据流、算法和系统行为。' if diagrams else '按知识领域阅读笔记、设计、分析与实验。'
    entries=[item for item in ENTRIES if item['kind']!='关于我' and (not diagrams or item['kind'] in ('图解','交互图解','实验'))]
    options=''.join(f'<option value="{topic["id"]}">{topic["title"]}</option>' for topic in DATA['topics'])
    groups=[]
    for topic in DATA['topics']:
        rows='\n'.join(entry_row(item) for item in entries if item['topic']==topic['id'])
        if rows: groups.append(f'<section class="lf-directory-group" id="{topic["id"]}" data-lf-group><h2>{topic["title"]}</h2>{rows}</section>')
    content=f'''<header class="lf-page-heading"><span class="lf-kicker">{'VISUAL NOTES / LABS' if diagrams else 'KNOWLEDGE / INDEX'}</span><h1 class="lf-title">{title}</h1><p class="lf-lead">{description}</p></header>
<div class="lf-filter-bar" data-lf-filters hidden><label>筛选标题与摘要<input type="search" placeholder="例如 CUDA、拓扑、AllGather" aria-describedby="lf-result-count"></label><label>知识领域<select><option value="">全部专题</option>{options}</select></label></div>
<p class="lf-result-count" id="lf-result-count" role="status" aria-live="polite">共 {len(entries)} 篇内容</p>
<p class="lf-empty" id="lf-empty" hidden>没有匹配的内容。试试更短的关键词，或选择全部专题。</p>
<div class="lf-section">{''.join(groups)}</div>'''
    OUTPUTS[path]=document(path,title,description,content,'diagrams' if diagrams else 'topics')

def doc_collections():
    for collection in DATA['collections']:
        cid=collection['id']; path=f'{cid}/index.html'; base=prefix(path)
        extra=f'<link rel="stylesheet" href="{base}assets/css/docs.css">'
        scripts=['assets/js/content-data.js','assets/js/docs.js','assets/vendor/docsify/docsify.min.js']
        # Docsify already supplies Prism plus markup/clike. Loading prism-core again
        # erases those grammars and breaks C/C++ and Markdown dependencies.
        scripts += [f'assets/vendor/docsify/prism-{language}.min.js' for language in ['c','cpp','python','bash','json','markdown']]
        scripts += ['assets/vendor/docsify/search.min.js','assets/vendor/docsify/zoom-image.min.js']
        tags='\n'.join(f'<script src="{base}{script}"></script>' for script in scripts)
        OUTPUTS[path]=f'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{esc(collection['description'])}"><title>{esc(collection['title'])} · Linkforfuture</title>
<link rel="stylesheet" href="{base}assets/vendor/docsify/vue.css">
{head(path,extra)}</head><body class="lf-site lf-docs" data-collection="{cid}" data-page="{cid}">
<!-- Generated by scripts/build_site.py. Shared config: assets/js/docs.js. -->
{header(path,'work' if cid=='work' else 'topics')}
<div id="lf-content"><div id="app">正在加载{esc(collection['title'])}…</div></div>
<noscript><div class="lf-container"><p>文档阅读需要 JavaScript。也可以<a href="https://github.com/linkforfuture/linkforfuture.github.io/tree/main/{cid}">在 GitHub 阅读原始文档</a>。</p></div></noscript>
{footer(path)}
{tags}
</body></html>
'''
        sidebar=['<!-- Generated from content-index.json by scripts/build_site.py. -->','']
        last=None
        for item in ENTRIES:
            if item.get('collection')!=cid: continue
            if item['group']!=last:
                last=item['group']; sidebar += ['', '- '+last]
            sidebar.append(f"  - [{item['title']}]({item['source'][len(cid)+1:]})")
        OUTPUTS[f'{cid}/_sidebar.md']='\n'.join(sidebar).strip()+'\n'
        OUTPUTS[f'{cid}/_404.md']='# 没有找到这篇文档\n\n请从专题目录重新选择，或[返回专题首页](README.md)。\n'

def replace_block(text,name,content):
    pattern=rf'<!-- LF:{name} -->.*?<!-- /LF:{name} -->'
    result,count=re.subn(pattern,lambda _:f'<!-- LF:{name} -->\n{content}\n<!-- /LF:{name} -->',text,flags=re.S)
    if count!=1: raise ValueError(f'Expected one LF:{name} block; found {count}')
    return result

def html_shells():
    for item in ENTRIES:
        if not item['source'].endswith('.html'): continue
        path=item['source']; text=(ROOT/path).read_text(encoding='utf-8'); base=prefix(path)
        active='about' if item['kind']=='关于我' else ('diagrams' if item['kind'] in ['交互图解','图解'] else 'topics')
        legacy=re.search(r'data-legacy="([^"]+)"',text)
        if legacy:
            extra=f'<link rel="stylesheet" href="{base}assets/css/pages/{legacy.group(1)}.css">\n<link rel="stylesheet" href="{base}assets/css/legacy.css">'
        else:
            # New article/interactive templates already use public lf-* components.
            extra=''
        text=replace_block(text,'HEAD',head(path,extra))
        topic=TOPICS[item['topic']]
        breadcrumb=f'<div class="lf-container"><div class="lf-breadcrumb"><a href="{base}topics.html">专题</a> / <a href="{base}topics.html#{topic["id"]}">{topic["title"]}</a> / {esc(item["title"])}</div></div>'
        text=replace_block(text,'HEADER',header(path,active)+('\n'+breadcrumb if active!='about' else ''))
        text=replace_block(text,'FOOTER',footer(path))
        OUTPUTS[path]=text

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    homepage(); directory(); directory(True); doc_collections(); html_shells()
    OUTPUTS['assets/js/content-data.js']='// Generated from content-index.json. Do not edit.\nwindow.LF_CONTENT = '+json.dumps(DATA,ensure_ascii=False,separators=(',',':'))+';\n'
    changed=[]
    for name,content in OUTPUTS.items():
        path=ROOT/name
        if path.exists() and path.read_text(encoding='utf-8')==content: continue
        changed.append(name)
        if not args.check:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding='utf-8',newline='\n')
    if args.check and changed:
        print('Generated files are stale:\n'+'\n'.join(changed)); raise SystemExit(1)
    print(f'{"Checked" if args.check else "Built"} {len(OUTPUTS)} files; {len(changed)} changed.')

if __name__=='__main__': main()
