"""Build shared shells, navigation and directories with Python's standard library.

Run from any directory: python scripts/build_site.py [--check]
Existing article bodies and interactions are never regenerated.
"""
from pathlib import Path
import argparse
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'content-index.json').read_text(encoding='utf-8'))
TOPICS = {item['id']: item for item in DATA['topics']}
SECTIONS = {item['id']: item for item in DATA['sections']}
ENTRIES = DATA['entries']
OUTPUTS = {}

def esc(value):
    return html.escape(str(value), quote=True)

def prefix(path):
    return '../' * (len(Path(path).parts) - 1)

def head(path, extra=''):
    base = prefix(path)
    return '\n'.join([
        f'<link rel="stylesheet" href="{base}assets/css/tokens.css">',
        f'<link rel="stylesheet" href="{base}assets/css/site.css">', extra,
        f'<script src="{base}assets/js/site.js" defer></script>'
    ])

def header(path, active, target='lf-content'):
    base = prefix(path)
    links = [('index.html','首页','home')] + [(item['url'],item['title'],item['id']) for item in DATA['sections']]
    nav = ''.join(f'<a href="{base}{url}"'+(' aria-current="page"' if key == active else '')+f'>{label}</a>' for url,label,key in links)
    return f'''<a class="lf-skip" href="#{target}">跳到正文</a>
<header class="lf-header"><div class="lf-header-inner">
  <a class="lf-brand" href="{base}index.html"><span class="lf-brand-mark" aria-hidden="true">L</span>Linkforfuture</a>
  <div class="lf-nav" role="navigation" aria-label="全站导航">{nav}</div>
  <details class="lf-menu"><summary>导航</summary><div class="lf-nav" role="navigation" aria-label="移动端全站导航">{nav}</div></details>
</div></header>'''

def footer(path):
    base = prefix(path)
    return f'''<footer class="lf-footer"><div class="lf-footer-inner"><span>Linkforfuture · 记录工作、学习与思考 · 持续生长</span><div class="lf-footer-links"><a href="https://github.com/linkforfuture">GitHub ↗</a><a href="{base}about.html">关于这个小站</a></div></div></footer>'''

def document(path, title, description, content, active, scripts=''):
    return f'''<!doctype html>
<html lang="zh-CN"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{esc(description)}"><title>{esc(title)} · Linkforfuture</title>
{head(path)}
</head><body class="lf-site" data-page="{active}">
<!-- Generated by scripts/build_site.py. Edit content-index.json or the generator, then rebuild. -->
{header(path,active)}
<main class="lf-container" id="lf-content">{content}</main>
{footer(path)}{scripts}
</body></html>
'''

def entry_row(item):
    topic = TOPICS[item['topic']]['title']
    return f'''<article class="lf-entry" data-lf-entry data-topic="{esc(item['topic'])}"><div><a class="lf-entry-title" href="{esc(item['url'])}">{esc(item['title'])}</a><p>{esc(item['summary'])}</p></div><div class="lf-entry-meta"><span>{esc(topic)}</span><span class="lf-tag">{esc(item['kind'])}</span></div></article>'''

def homepage():
    cards=''.join(f'''<a class="lf-space-card" href="{esc(section['url'])}"><span class="lf-kicker">{esc(section['label'])}</span><h3>{esc(section['title'])}</h3><p>{esc(section['description'])}</p><span class="lf-space-link">{esc(section['title'])} →</span></a>''' for section in DATA['sections'])
    content=f'''<section class="lf-home-hero"><div><span class="lf-kicker">LINKFORFUTURE / PERSONAL SPACE</span><p class="lf-hello">你好，欢迎来我的小站。</p><h1 class="lf-title lf-person-name">我是 Linkforfuture<span class="lf-name-dot">。</span></h1><p class="lf-lead">在这里，记录工作、学习与思考。<br>把做过的事、学到的东西，慢慢留存下来。</p><div class="lf-actions"><a class="lf-button lf-button-primary" href="about.html">认识我 →</a><a class="lf-button" href="https://github.com/linkforfuture">GitHub ↗</a></div></div><div class="lf-person-mark" aria-hidden="true"><span>L<span class="lf-name-dot">.</span></span><small>持续生长</small></div></section>
<section class="lf-section lf-home-spaces" aria-labelledby="lf-spaces-title"><div class="lf-section-head"><h2 id="lf-spaces-title">在这里逛逛</h2><span>关于我，也关于我在做的事</span></div><div class="lf-space-grid">{cards}</div></section>'''
    OUTPUTS['index.html']=document('index.html','个人主页','Linkforfuture 的个人主页，记录工作、学习与思考。',content,'home')

def aboutpage():
    content='''<header class="lf-page-heading"><span class="lf-kicker">ABOUT ME</span><h1 class="lf-title">你好，我是 Linkforfuture。</h1><p class="lf-lead">欢迎来到我的个人主页。</p></header>
<article class="lf-prose lf-about lf-section"><h2>关于我</h2><p>我的工作与 HCCL 集合通信相关。工作中的设计、问题分析，以及平时的学习记录，都慢慢整理到了这里。</p><p>这个小站是我的个人空间，用来留下工作、学习与思考的痕迹。</p><h2>这个小站里有什么</h2><p><a href="work/">工作</a>里是做过的需求、设计和分析；<a href="topics.html">学习</a>里是笔记、动手实验和图解。你可以从感兴趣的地方开始逛。</p><h2>在别处找到我</h2><p><a href="https://github.com/linkforfuture">GitHub · Linkforfuture ↗</a></p><h2>其他资料</h2><p><a href="resume-weixin_43960572.html">简历草稿与学习计划 →</a></p><p class="lf-about-note">这份简历是可编辑的整理稿，其中仍有待补全的信息。</p></article>'''
    OUTPUTS['about.html']=document('about.html','关于我','认识 Linkforfuture，以及这个记录工作、学习与思考的小站。',content,'about')

def directory(diagrams=False):
    path='diagrams.html' if diagrams else 'topics.html'
    title='图解实验' if diagrams else '学习'
    description='在图解与实验中理解数据流、算法和系统行为。' if diagrams else '我的学习笔记、动手实验，以及用来帮助理解的图解。'
    entries=[item for item in ENTRIES if item['section']=='learning' and (not diagrams or item['kind'] in ('图解','交互图解','实验'))]
    options=''.join(f'<option value="{topic["id"]}">{topic["title"]}</option>' for topic in DATA['topics'])
    groups=[]
    for topic in DATA['topics']:
        rows='\n'.join(entry_row(item) for item in entries if item['topic']==topic['id'])
        if rows: groups.append(f'<section class="lf-directory-group" id="{topic["id"]}" data-lf-group><h2>{topic["title"]}</h2>{rows}</section>')
    subnav='<a href="topics.html">← 返回学习</a>' if diagrams else '<a href="diagrams.html">图解实验 →</a><a href="cuda/">CUDA 学习记录 →</a><a href="leetcode/">算法笔记 →</a>'
    content=f'''<div class="lf-breadcrumb"><a href="index.html">首页</a> / {'<a href="topics.html">学习</a> / 图解实验' if diagrams else '学习'}</div><header class="lf-page-heading lf-heading-after-crumb"><span class="lf-kicker">{'LEARNING / LABS' if diagrams else 'LEARNING'}</span><h1 class="lf-title">{title}</h1><p class="lf-lead">{description}</p><div class="lf-local-nav" aria-label="学习板块">{subnav}</div></header>
<div class="lf-filter-bar" data-lf-filters hidden><label>筛选标题与摘要<input type="search" placeholder="例如 CUDA、拓扑、AllGather" aria-describedby="lf-result-count"></label><label>知识领域<select><option value="">全部专题</option>{options}</select></label></div>
<p class="lf-result-count" id="lf-result-count" role="status" aria-live="polite">共 {len(entries)} 篇内容</p>
<p class="lf-empty" id="lf-empty" hidden>没有匹配的内容。试试更短的关键词，或选择全部专题。</p>
<div class="lf-section">{''.join(groups)}</div>'''
    OUTPUTS[path]=document(path,title,description,content,'learning')

def doc_collections():
    for collection in DATA['collections']:
        cid=collection['id']; path=f'{cid}/index.html'; base=prefix(path)
        extra=f'<link rel="stylesheet" href="{base}assets/css/docs.css">'
        scripts=['assets/js/content-data.js','assets/js/docs.js','assets/vendor/docsify/docsify.min.js']
        # Docsify already supplies Prism plus markup/clike. Loading prism-core again
        # erases those grammars and breaks C/C++ and Markdown dependencies.
        scripts += [f'assets/vendor/docsify/prism-{language}.min.js' for language in ['c','cpp','python','bash','json','markdown']]
        scripts += ['assets/vendor/docsify/search.min.js','assets/vendor/docsify/zoom-image.min.js']
        tags='\n'.join(f'<script src="{base}{script}"></script>' for script in scripts)
        OUTPUTS[path]=f'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{esc(collection['description'])}"><title>{esc(collection['title'])} · Linkforfuture</title>
<link rel="stylesheet" href="{base}assets/vendor/docsify/vue.css">
{head(path,extra)}</head><body class="lf-site lf-docs" data-collection="{cid}" data-page="{cid}">
<!-- Generated by scripts/build_site.py. Shared config: assets/js/docs.js. -->
{header(path,collection['section'])}
<div id="lf-content"><div id="app">正在加载{esc(collection['title'])}…</div></div>
<noscript><div class="lf-container"><p>文档阅读需要 JavaScript。也可以<a href="https://github.com/linkforfuture/linkforfuture.github.io/tree/main/{cid}">在 GitHub 阅读原始文档</a>。</p></div></noscript>
{footer(path)}
{tags}
</body></html>
'''
        sidebar=['<!-- Generated from content-index.json by scripts/build_site.py. -->','']
        last=None
        for item in ENTRIES:
            if item.get('collection')!=cid: continue
            if item['group']!=last:
                last=item['group']; sidebar += ['', '- '+last]
            sidebar.append(f"  - [{item['title']}]({item['source'][len(cid)+1:]})")
        OUTPUTS[f'{cid}/_sidebar.md']='\n'.join(sidebar).strip()+'\n'
        OUTPUTS[f'{cid}/_404.md']='# 没有找到这篇文档\n\n请从专题目录重新选择，或[返回专题首页](README.md)。\n'

def replace_block(text,name,content):
    pattern=rf'<!-- LF:{name} -->.*?<!-- /LF:{name} -->'
    result,count=re.subn(pattern,lambda _:f'<!-- LF:{name} -->\n{content}\n<!-- /LF:{name} -->',text,flags=re.S)
    if count!=1: raise ValueError(f'Expected one LF:{name} block; found {count}')
    return result

def html_shells():
    for item in ENTRIES:
        if not item['source'].endswith('.html'): continue
        path=item['source']; text=(ROOT/path).read_text(encoding='utf-8'); base=prefix(path)
        active=item['section']
        legacy=re.search(r'data-legacy="([^"]+)"',text)
        if legacy:
            extra=f'<link rel="stylesheet" href="{base}assets/css/pages/{legacy.group(1)}.css">\n<link rel="stylesheet" href="{base}assets/css/legacy.css">'
        else:
            # New article/interactive templates already use public lf-* components.
            extra=''
        text=replace_block(text,'HEAD',head(path,extra))
        topic=TOPICS[item['topic']]
        section=SECTIONS[active]
        topic_link=f' / <a href="{base}topics.html#{topic["id"]}">{topic["title"]}</a>' if active=='learning' else ''
        breadcrumb=f'<div class="lf-container"><div class="lf-breadcrumb"><a href="{base}{section["url"]}">{section["title"]}</a>{topic_link} / {esc(item["title"])}</div></div>'
        text=replace_block(text,'HEADER',header(path,active)+('\n'+breadcrumb if active!='about' else ''))
        text=replace_block(text,'FOOTER',footer(path))
        OUTPUTS[path]=text

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    homepage(); aboutpage(); directory(); directory(True); doc_collections(); html_shells()
    OUTPUTS['assets/js/content-data.js']='// Generated from content-index.json. Do not edit.\nwindow.LF_CONTENT = '+json.dumps(DATA,ensure_ascii=False,separators=(',',':'))+';\n'
    changed=[]
    for name,content in OUTPUTS.items():
        path=ROOT/name
        if path.exists() and path.read_text(encoding='utf-8')==content: continue
        changed.append(name)
        if not args.check:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding='utf-8',newline='\n')
    if args.check and changed:
        print('Generated files are stale:\n'+'\n'.join(changed)); raise SystemExit(1)
    print(f'{"Checked" if args.check else "Built"} {len(OUTPUTS)} files; {len(changed)} changed.')

if __name__=='__main__': main()
